echo
echo DO THIS MANUALLY - DO THIS MANUALLY
echo
echo UPDATE ORATAB IN ALL NODES TO POINT TO 12C HOME
echo For DB_UNIQUE_NAME and INSTANCE_NAME entries
echo
echo DO THIS MANUALLY - DO THIS MANUALLY
echo
